# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub" # Flutter/Dart dependencies
    directory: "/" # Location of pubspec.yaml
    schedule:
      interval: "weekly" # Frequency of updates
    open-pull-requests-limit: 5 # Max number of open PRs at a time
